image: Ubuntu1804  # Build environment image

stack: node 12  # Node.js version

branches:
  only:
    - main  # Git branch to build from

cache:
  - node_modules  # Cache node_modules directory for faster builds

install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - source "$NVM_DIR/nvm.sh"
  - nvm install $(<.nvmrc) 
  - nvm use $(<.nvmrc)      
  - yarn

build_script:
  - yarn build  # Command to build the project (if needed)

test_script:
  - yarn lint && yarn test  # Command to run linting and tests
  - yarn start &  # Start the application in the background
  - sleep 3  # Wait for the application to start
  - yarn e2e  # Run end-to-end tests

artifacts:
  - path: dist
    name: artifact  # Specify artifacts to be saved

deploy_script:
  - echo "Configuring Git..."
  - git config --global credential.helper store
  - git config --global user.name "Roman9456"
  - git config --global user.email "smolyakov_ra@mail.ru"
  - echo "https://${GITHUB_TOKEN}:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - echo "Contents of dist directory:"
  - ls -al dist
  - echo "Checking for changes in the build..."
  - if git diff --quiet --exit-code; then echo "No changes detected in the build. Skipping deployment."; exit 0; fi
  - echo "Deploying to GitHub Pages..."
  - git clone --branch gh-pages https://github.com/Roman9456/credit-card-validator gh-pages
  - rm -rf gh-pages/*
  - cp -r dist/* gh-pages/
  - echo "Contents of gh-pages directory:"
  - ls -al gh-pages
  - echo "Untracked files in working directory:"
  - git status --porcelain
  - cd gh-pages
  - if git diff --quiet --exit-code; then echo "No changes detected in gh-pages directory. Skipping deployment."; exit 0; fi
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push origin gh-pages
  - echo "Deployment complete."
