image: Ubuntu1804

branches:
  only:
    - main 

init:
  - echo "Installing NVM..."
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - source "$NVM_DIR/nvm.sh"
  - echo "Installing Node.js..."
  - nvm install 16
  - nvm use 16

install:
  - echo "Installing dependencies..."
  - yarn install  

build_script:
  - echo "Building the project..."
  - yarn build  

test_script:
  - echo "Running tests..."
  - yarn test  

deploy_script:
  - echo "Deploying to GitHub Pages..."
  - git clone --branch gh-pages git@github.com:Roman9456/credit-card-validator gh-pages-temp
  - cd gh-pages-temp
  - git rm -rf .
  - cd ..
  - cp -r dist/. gh-pages-temp
  - cd gh-pages-temp
  - git config user.name "AppVeyor"
  - git config user.email "ci@appveyor.com"
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push origin HEAD:gh-pages --force
  - cd ..
  - rm -rf gh-pages-temp
  - echo "Deployment complete."
