image: Ubuntu1804

branches:
  only:
    - main

stack: node 16

init:
  - echo "Installing NVM..."
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - source "$NVM_DIR/nvm.sh"
  - echo "Installing Node.js..."
  - nvm install 18.12.0
  - nvm use 18.12.0
  - node --version  

install:
  - echo "Installing dependencies..."
  - yarn install

build_script:
  - echo "Building the project..."
  - yarn run build

test_script:
  - echo "Running linting and unit tests..."
  - yarn lint
  - yarn test

deploy_script:
  - echo "Deploying to GitHub Pages..."
  - git clone --branch gh-pages https://github.com/Roman9456/credit-card-validator gh-pages
  - rm -rf gh-pages/*
  - cp -r dist/* gh-pages/
  - cd gh-pages
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push origin gh-pages
  - echo "Deployment complete."
