image: Ubuntu1804

branches:
  only:
    - main

init:
  - echo "Installing NVM..."
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - source "$NVM_DIR/nvm.sh"
  - echo "Installing Node.js..."
  - nvm install 16
  - nvm use 16

install:
  - echo "Installing dependencies..."
  - yarn install  

build_script:
  - echo "Building the project..."
  - yarn build  

test_script:
  - echo "Running tests..."
  - yarn test  

deploy_script:
  - echo "Deploying to GitHub Pages..."
  - git clone --branch gh-pages git@github.com:Roman9456/credit-card-validator gh-pages
  - rm -rf gh-pages/*
  - cp -r dist/* gh-pages/
  - cd gh-pages
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push origin gh-pages
  - echo "Deployment complete."
