image: Ubuntu1804

branches:
  only:
    - main 

init:
  - echo "Installing NVM..."
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - source "$NVM_DIR/nvm.sh"
  - echo "Installing Node.js..."
  - nvm install 16
  - nvm use 16

install:
  - echo "Installing dependencies..."
  - yarn install  

build_script:
  - echo "Building the project..."
  - yarn build  

test_script:
  - echo "Running tests..."
  - yarn test  

deploy_script:
  - echo "Deploying to GitHub Pages..."
  - cp -r dist/* .  # Copy contents of dist directory to root
  - git config user.name "AppVeyor"  # Configure Git user name
  - git config user.email "ci@appveyor.com"  # Configure Git user email
  - git config credential.helper "store --file=$HOME/.git-credentials"  # Set Git credential helper
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"  # Setup Git credentials
  - git push origin HEAD:gh-pages  # Push changes to gh-pages branch
  - echo "Deployment complete."