image: Ubuntu1804

branches:
  only:
    - main

init:
  - echo "Installing NVM..."
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - source "$NVM_DIR/nvm.sh"
  - echo "Installing Node.js..."
  - nvm install 16
  - nvm use 16

install:
  - echo "Installing dependencies..."
  - yarn install  

build_script:
  - echo "Building the project..."
  - yarn build  

test_script:
  - echo "Running tests..."
  - yarn test  

deploy_script:
  - echo "Deploying to GitHub Pages..."
  - git clone --branch gh-pages https://github.com/Roman9456/credit-card-validator gh-pages
  - rm -rf gh-pages/*
  - cp -r dist/* gh-pages/
  - cd gh-pages
  - git config user.email "smolyakov_ra@mail.ru"
  - git config user.name "Roman9456"
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push origin gh-pages
  - echo "Deployment complete."
