version: 1.0.{build}
image: Visual Studio 2019
platform:
  - x64
configuration:
  - Release
before_build:
  - ps: Install-Product node $env:nodejs_version
  - npm install
build_script:
  - npm run build
test_script:
  - npm test
artifacts:
  - path: dist
deploy:
  provider: GitHub
  auth_token:
    secure: your_github_token
  on:
    branch: main
